micronaut:
    application:
        name: example-micronaut-java
                
#Uncomment to set server port
#    server:
#        port: 8080


#datasources:
#    default:
#        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#        username: sa
#        password: ""
#        driverClassName: org.h2.Driver



#postgres:
#    reactive:
#        client:
#            port: 5432
#            host: the-host
#            database: the-db
#            user: test
#            password: test
#            maxSize: 5